# Generated by Django 5.1.7 on 2025-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('is_break', models.BooleanField(default=False, verbose_name='是否借出')),
                ('user_id', models.IntegerField(default=0, verbose_name='借出人')),
                ('break_date', models.DateTimeField(auto_now=True, verbose_name='借出时间')),
                ('return_date', models.DateTimeField(auto_now=True, verbose_name='还书时间')),
            ],
            options={
                'verbose_name': '图书',
                'db_table': 'book',
            },
        ),
    ]
