# Generated by Django 5.1.7 on 2025-03-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='break_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='借出时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='还书时间'),
        ),
    ]
